import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae2fd",
        surface: "#0b1326",
        "tertiary-container": "#d8e3fb",
        "tertiary-fixed": "#d8e3fb",
        "on-error-container": "#ffdad6",
        primary: "#ffffff",
        "on-surface-variant": "#c4c7c8",
        "surface-container-low": "#131b2e",
        "on-background": "#dae2fd",
        "outline-variant": "#444748",
        "surface-container-lowest": "#060e20",
        "on-primary-container": "#636565",
        "on-tertiary-fixed": "#111c2d",
        "surface-container-high": "#222a3d",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-error": "#690005",
        "on-surface": "#dae2fd",
        "primary-fixed": "#e2e2e2",
        "primary-container": "#e2e2e2",
        "on-secondary-fixed-variant": "#39485a",
        "on-primary-fixed-variant": "#454747",
        background: "#0b1326",
        "secondary-fixed-dim": "#b9c8de",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
        secondary: "#b9c8de",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "on-secondary": "#233143",
        "surface-tint": "#c6c6c7",
        "on-secondary-fixed": "#0d1c2d",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary": "#263143",
        "on-primary": "#2f3131",
        "inverse-on-surface": "#283044",
        "on-secondary-container": "#a7b6cc",
        error: "#ffb4ab",
        "on-primary-fixed": "#1a1c1c",
        "inverse-primary": "#5d5f5f",
        "secondary-container": "#39485a",
        "primary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#5a6579",
        tertiary: "#ffffff",
        "secondary-fixed": "#d4e4fa",
        "surface-dim": "#0b1326",
        outline: "#8e9192",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "container-max": "1440px",
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "headline-lg": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["Geist"],
        "body-sm": ["Geist"],
        display: ["Geist"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
